# Project: Datei_test
# Makefile created by Dev-C++ 5.4.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = datei_test.o
LINKOBJ  = datei_test.o
LIBS     = -L"H:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"H:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"H:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = Datei_test.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

datei_test.o: datei_test.c
	$(CC) -c datei_test.c -o datei_test.o $(CFLAGS)
