#include <stdio.h>
#include <stdlib.h>

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	int links(){
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                   _____                                                       \n");
	printf("                   |-_-|                                                       \n");
	printf("                   |___|                                                       \n");
	printf("                     |   |_|                                                   \n");
	printf("                  ___|___ |                                                    \n");
	printf("                  |     |/                                                     \n");
	printf("                 /|     |                                                      \n");
	printf("                | |     |                                                      \n");
	printf("                _ |_____|                                                      \n");
	printf("               / ||  |  |                                                      \n");
	printf("                  |  |  |                                                      \n");
	printf("                  |  |  |                                                      \n");
	printf("                 _|  |  |_                                                     \n");
	printf("                |____|____|                                                    \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	sleep(0.05);
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                    _____                                                      \n");
	printf("                    |._.|                                                      \n");
	printf("                    |___|                                                      \n");
	printf("                      /   |_/                                                  \n");
	printf("                  ___|___ |                                                    \n");
	printf("                  |     |/                                                     \n");
	printf("                 /|     |                                                      \n");
	printf("                | |     |                                                      \n");
	printf("                _ |_____|                                                      \n");
	printf("               | ||  |  |                                                      \n");
	printf("                  |  |  |                                                      \n");
	printf("                  |  |  |                                                      \n");
	printf("                 _|  |  |/|                                                    \n");
	printf("                |____|___/                                                     \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	sleep(0.05);
	}
	int mitte(){
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                 _____                                         \n");
	printf("                                 |-_-|                                         \n");
	printf("                                 |___|                                         \n");
	printf("                                   |   |_|                                     \n");
	printf("                                ___|___ |                                      \n");
	printf("                                |     |/                                       \n");
	printf("                               /|     |                                        \n");
	printf("                              | |     |                                        \n");
	printf("                              _ |_____|                                        \n");
	printf("                             / ||  |  |                                        \n");
	printf("                                |  |  |                                        \n");
	printf("                                |  |  |                                        \n");
	printf("                               _|  |  |_                                       \n");
	printf("                              |____|____|                                      \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	sleep(0.05);
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                  _____                                        \n");
	printf("                                  |._.|                                        \n");
	printf("                                  |___|                                        \n");
	printf("                                    /  |_/                                     \n");
	printf("                                ___|___ |                                      \n");
	printf("                                |     |/                                       \n");
	printf("                               /|     |                                        \n");
	printf("                              | |     |                                        \n");
	printf("                              _ |_____|                                        \n");
	printf("                             | ||  |  |                                        \n");
	printf("                                |  |  |                                        \n");
	printf("                                |  |  |                                        \n");
	printf("                               _|  |  |/|                                      \n");
	printf("                              |____|____/                                      \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	sleep(0.05);
}
	int rechts(){
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                              _____                            \n");
	printf("                                              |._.|                            \n");
	printf("                                              |___|                            \n");
	printf("                                                /  |_/                         \n");
	printf("                                            ___|___ |                          \n");
	printf("                                            |     |/                           \n");
	printf("                                           /|     |                            \n");
	printf("                                          | |     |                            \n");
	printf("                                          _ |_____|                            \n");
	printf("                                         | ||  |  |                            \n");
	printf("                                            |  |  |                            \n");
	printf("                                            |  |  |                            \n");
	printf("                                           _|  |  |/|                          \n");
	printf("                                          |____|___/                           \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	sleep(0.05);
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                             _____                             \n");
	printf("                                             |-_-|                             \n");
	printf("                                             |___|                             \n");
	printf("                                               |   |_|                         \n");
	printf("                                            ___|___ |                          \n");
	printf("                                            |     |/                           \n");
	printf("                                           /|     |                            \n");
	printf("                                          | |     |                            \n");
	printf("                                          _ |_____|                            \n");
	printf("                                         / ||  |  |                            \n");
	printf("                                            |  |  |                            \n");
	printf("                                            |  |  |                            \n");
	printf("                                           _|  |  |_                           \n");
	printf("                                          |____|____|                          \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	printf("                                                                               \n");
	sleep(0.05);
	}
	do{
		links();
		links();
		links();
		links();
		mitte();
		mitte();
		rechts();
		rechts();
		rechts();
		rechts();
		mitte();
		mitte();
	}while(1>0);
	return 0;
}
